on: [push]

name: CI

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    name: Build scheduler app release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Clippy
        run: cargo clippy --all-targets --all-features
      - name: Build
        run: cargo build --release --all-features
  docker-build:
    name: Build scheduler app docker image
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: false
          tags: scheduler:ci
