on: [push]

name: CI

jobs:
  build:
    name: Build scheduler app release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cargo build --release --all-features
